/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Controlador.clsBitacora;
import Controlador.clsUsuarioConectado;
import Modelo.Conexion;
import java.awt.Dimension;
import java.io.File;
import java.sql.Connection;
import java.util.HashMap;
import java.util.Map;
import javax.swing.JOptionPane;


/**
 *
 * @author visitante
 */
public class MdiGeneral extends javax.swing.JFrame {

    /**
     * Creates new form MdiGeneral
     */
    public MdiGeneral() {
        initComponents();
        setLocationRelativeTo(null);
        this.setExtendedState(MdiGeneral.MAXIMIZED_BOTH);
        this.setTitle("Menu Gestión de Ventas");
        setDefaultCloseOperation(EXIT_ON_CLOSE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1MdiVentas = new javax.swing.JMenuItem();
        jMenuItem2MdiVentas = new javax.swing.JMenuItem();
        jMenuItem4MdiVentas = new javax.swing.JMenuItem();
        jCheckBoxMenuItem1MdiVentas = new javax.swing.JCheckBoxMenuItem();
        jMenu1MdiVentas = new javax.swing.JMenu();
        jDesktopPaneVentas = new javax.swing.JDesktopPane();
        mnuGeneralVentas = new javax.swing.JMenuBar();
        mnuArchivo = new javax.swing.JMenu();
        mnuSalirSistema = new javax.swing.JCheckBoxMenuItem();
        mnuCatalogos = new javax.swing.JMenu();
        mnuCatalogosMantenimientosVentas = new javax.swing.JMenu();
        mantenimientoEntrenador = new javax.swing.JCheckBoxMenuItem();
        mnuConsultas = new javax.swing.JMenu();
        mnuReportes = new javax.swing.JMenu();
        mnuAyudas = new javax.swing.JMenu();
        mnuAyudaMDI = new javax.swing.JMenuItem();

        jMenuItem1MdiVentas.setText("jMenuItem1");

        jMenuItem2MdiVentas.setText("jMenuItem2");

        jMenuItem4MdiVentas.setText("jMenuItem4");

        jCheckBoxMenuItem1MdiVentas.setSelected(true);
        jCheckBoxMenuItem1MdiVentas.setText("jCheckBoxMenuItem1");

        jMenu1MdiVentas.setText("jMenu1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout jDesktopPaneVentasLayout = new javax.swing.GroupLayout(jDesktopPaneVentas);
        jDesktopPaneVentas.setLayout(jDesktopPaneVentasLayout);
        jDesktopPaneVentasLayout.setHorizontalGroup(
            jDesktopPaneVentasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jDesktopPaneVentasLayout.setVerticalGroup(
            jDesktopPaneVentasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 279, Short.MAX_VALUE)
        );

        mnuArchivo.setText("Archivo");
        mnuArchivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuArchivoActionPerformed(evt);
            }
        });

        mnuSalirSistema.setSelected(true);
        mnuSalirSistema.setText("Salir del Sistema");
        mnuSalirSistema.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuSalirSistemaActionPerformed(evt);
            }
        });
        mnuArchivo.add(mnuSalirSistema);

        mnuGeneralVentas.add(mnuArchivo);

        mnuCatalogos.setText("Catalogos");

        mnuCatalogosMantenimientosVentas.setText("Mantenimientos");
        mnuCatalogosMantenimientosVentas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuCatalogosMantenimientosVentasActionPerformed(evt);
            }
        });

        mantenimientoEntrenador.setSelected(true);
        mantenimientoEntrenador.setText("Mantenimiento Entrenador");
        mantenimientoEntrenador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mantenimientoEntrenadorActionPerformed(evt);
            }
        });
        mnuCatalogosMantenimientosVentas.add(mantenimientoEntrenador);

        mnuCatalogos.add(mnuCatalogosMantenimientosVentas);

        mnuGeneralVentas.add(mnuCatalogos);

        mnuConsultas.setText("Consultas");
        mnuConsultas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuConsultasActionPerformed(evt);
            }
        });
        mnuGeneralVentas.add(mnuConsultas);

        mnuReportes.setText("Reportes");
        mnuGeneralVentas.add(mnuReportes);

        mnuAyudas.setText("Ayudas");
        mnuAyudas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuAyudasActionPerformed(evt);
            }
        });

        mnuAyudaMDI.setText("Ayuda MDI ");
        mnuAyudaMDI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuAyudaMDIActionPerformed(evt);
            }
        });
        mnuAyudas.add(mnuAyudaMDI);

        mnuGeneralVentas.add(mnuAyudas);

        setJMenuBar(mnuGeneralVentas);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPaneVentas)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPaneVentas)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mnuCatalogosMantenimientosVentasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuCatalogosMantenimientosVentasActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_mnuCatalogosMantenimientosVentasActionPerformed

    private void mnuArchivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuArchivoActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_mnuArchivoActionPerformed

    private void mnuSalirSistemaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuSalirSistemaActionPerformed
        // TODO add your handling code here:
                /*===== OPERACIÓN CERRAR SESIÓN ====
          Variable entera respuesta_cs*/

        int respuesta_cs = JOptionPane.showConfirmDialog(this, "¿Desea Cerrar Sesión?", "Cerrar Sesión",            JOptionPane.YES_NO_OPTION);

        if (respuesta_cs == 0) {
            this.dispose();
        }        
    }//GEN-LAST:event_mnuSalirSistemaActionPerformed

    private void mantenimientoEntrenadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mantenimientoEntrenadorActionPerformed
        // TODO add your handling code here:
        frmMantenimientoEntrenador ventana = new frmMantenimientoEntrenador ();
        jDesktopPaneVentas.add(ventana);
        Dimension desktopSize = jDesktopPaneVentas.getSize();
        Dimension FrameSize = ventana.getSize();
        ventana.setLocation((desktopSize.width - FrameSize.width) / 2, (desktopSize.height - FrameSize.             height) / 2);       
    }//GEN-LAST:event_mantenimientoEntrenadorActionPerformed

    private void mnuConsultasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuConsultasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mnuConsultasActionPerformed

    
    private void mnuAyudasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuAyudasActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_mnuAyudasActionPerformed

    private void mnuAyudaMDIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuAyudaMDIActionPerformed
        // TODO add your handling code here:
        //Carlos Javier Sandoval Catalán
        //9959-21-1324
                try {
            if ((new File("src\\main\\java\\ventas\\ayuda\\generalayudaventas.chm")).exists()) {
                Process p = Runtime
                .getRuntime()
                .exec("rundll32 url.dll,FileProtocolHandler src\\main\\java\\ventas\\ayuda\\generalayudaventas.chm");
                p.waitFor();
            } else {
                System.out.println("La ayuda no fue encontrada");
            }
            //System.out.println("Correcto");
        } catch (Exception ex) {
            ex.printStackTrace();
        }
    }//GEN-LAST:event_mnuAyudaMDIActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MdiGeneral.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MdiGeneral.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MdiGeneral.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MdiGeneral.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MdiGeneral().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem1MdiVentas;
    private javax.swing.JDesktopPane jDesktopPaneVentas;
    private javax.swing.JMenu jMenu1MdiVentas;
    private javax.swing.JMenuItem jMenuItem1MdiVentas;
    private javax.swing.JMenuItem jMenuItem2MdiVentas;
    private javax.swing.JMenuItem jMenuItem4MdiVentas;
    private javax.swing.JCheckBoxMenuItem mantenimientoEntrenador;
    private javax.swing.JMenu mnuArchivo;
    private javax.swing.JMenuItem mnuAyudaMDI;
    private javax.swing.JMenu mnuAyudas;
    private javax.swing.JMenu mnuCatalogos;
    private javax.swing.JMenu mnuCatalogosMantenimientosVentas;
    private javax.swing.JMenu mnuConsultas;
    private javax.swing.JMenuBar mnuGeneralVentas;
    private javax.swing.JMenu mnuReportes;
    private javax.swing.JCheckBoxMenuItem mnuSalirSistema;
    // End of variables declaration//GEN-END:variables
}
